POST http://localhost:4004/dev-challenge/Tests(ID=ac5607e0-5796-11ee-8c99-0242ac120002,IsActiveEntity=true)/DevChallengeService.assignQuestionsToTest
Content-Type: application/json

{"questionsCount":3}
